name: Unity EditMode CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  editmode-tests:
    name: Run edit mode tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}

      - name: Run EditMode tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: .
          unityVersion: 2022.3.25f1
          testMode: EditMode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          allowDirtyLicensing: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: editmode-test-results
          path: artifacts
