name: Unity CI
permissions:
  checks: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest     # Usa runners gratuitos de GitHub
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          

      - name: Clean test artifacts
        run: |
          rm -rf CodeCoverage
          rm -rf artifacts
      
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      
      - name: Run EditMode tests + Code Coverage
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.25f1
          testMode: EditMode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: |
            enableCodeCoverage
            generateHtmlReport
            generateAdditionalMetrics
          artifactsPath: ${{ github.workspace }}/CoverageResults
      
      - name: Convert coverage to lcov
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: ${{ github.workspace }}/CoverageResults/**/CoverageResults.json
          targetdir: ${{ github.workspace }}/CoverageLCOV
          reporttypes: 'LCOV'
          
      - name: Create/update coverage badge
        uses: threeal/coverage-badge-action@v2
        with:
          coverage-file: ${{ github.workspace }}/CoverageLCOV/lcov.info
          output: badge-coverage.svg
      
      - name: Commit badge
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: 'badge-coverage.svg'
          message: 'chore(ci): update coverage badge'
      
      - name: Build project (Windows)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL:   ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.25f1
          allowDirtyBuild: true
          versioning: None
      

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
